big file structure revamp. settings and globals got organized to help…
pappde/bmai pull request #62
Opened 2024-10-08 21:37 UTC by danlangford

big file structure revamp. settings and globals got organized to help… with dependency tree. fixes #44

im very new to C++ so I dont know if I have the proper use of `extern` and `inline` and `#pragma once` and "forwarding" and "precompiling" but I tried my best, it still compiles and passes its tests, and I am very open to feedback on how to improve it

2024-10-08 22:27 UTC, danlangford commented
I apologize for all the random #include commits. I guess my idea and tool chain does need all of those spelled out for some reason. glad that we have these automated builds to catch problems like that.

2024-10-09 14:57 UTC, pappde commented
It's a small project, so I wouldn't worry about precompiled headers.  The main thing to remember is that in C/C++ everything needs to be declared before it is used. That generally means either #include the header that defines the class, or you can forward declare (but only in cases where you have pointers only).  It's easier when you don't have circular dependencies.

The other thing that headers in turn will #include dependent headers, and you don't want a header to be included multiple times, so you either use #pragma once or a #ifndef/#define/#endif pattern around the header.

I'll review, but if it's compiling that's a good sign :)

2024-10-09 19:17 UTC, pappde requested changes
Overall looks good. The only thing is the main header for the "bmai_lib" module:
1) currently named "bmai.h", it would make more sense to call it "bmai_lib.h"
2) remove the main() declaration from that header file.

2024-10-09 19:35 UTC, pappde requested changes
GLOBALS
Recommendation is to get rid of the ones we can, and at least remove them from the header files. Definitely don't "inline" them.  The "inline" keyword will instance that in every CPP that #includes it.

Some specific ones:
1) BMC_Game g_game is only used by BMC_Parser, so just define the global in BMC_Parser.cpp, and remove it from the header.
2) g_ai_mode3: only used in BMC_Parser, so the same. In fact, this one already is instanced in BMC_Parser.cpp. You can again just remove it from the header.
3) g_ait_type should be defined in BMC_Parser.cpp and removed from the header.

Actually, I recommend deleting bmai_ai.h and then just seeing what you need to fix.

2024-10-09 19:35 UTC, pappde commented on src/BMC_Game.h
> +inline BMC_Game g_game(false);
Can't "inline" a global. You'll end up with one g_game in each CPP file that includes it.  See comments in bmai_ai.h

2024-10-09 19:35 UTC, pappde commented on src/bmai_ai.h
> +inline BMC_QAI	g_qai;
Need to change how globals are handled. For each global:
1) first identify if it even needs to be a global.  Can it just be locally owned?
E.g. "g_ai_type" is only used in BMC_Parser.  So you can just define it in BMC_Parser.cpp then you don't need to mention it in the header.

2) if it needs to be global, then:
2.1) instance it in a CPP file.  
E.g. BMC_Game.cpp defines "BMC_Game g_game"
2.2) "extern" it in the header file (like an export) so that other modules can link to it.
E.g. BMC_Game.h defines "extern BMC_Game g_game"

However, g_game is only used by BMC_Parser, so it can just be instanced there.

2024-10-09 19:39 UTC, pappde requested changes
A few more inlined globals noted.

2024-10-09 19:39 UTC, pappde commented on src/bmai_ai.h
> +inline BMC_QAI	g_qai;
Per other comment, I recommend:
1) move g_ai_type to BMC_Parser.cpp
2) delete bmai_ai.h

2024-10-09 19:39 UTC, pappde commented on src/BMC_Logger.h
> +inline BMC_Logger	g_logger;
1) instance in the CPP. I.e. "BMC_Logger g_logger;"
2) change to "extern" in the Header

2024-10-09 19:39 UTC, pappde commented on src/BMC_RNG.h
> +inline BMC_RNG		g_rng;
1) instance in the CPP
2) change header to "extern"

2024-10-09 19:39 UTC, pappde commented on src/BMC_Stats.h
> +inline BMC_Stats  g_stats;
1) instance in the CPP
2) change header to "extern"

2024-10-09 19:42 UTC, pappde commented
GLOBALS
I added several comments about how to handle globals. Unfortunately, a lot of redundant/overlapping comments since a lot of files in the commit, but I'll summarize again here.  

If you need a global (e.g. BMC_RNG g_rng is a good one)
1) pick a file to instance the global. Either BMC_RNG.cpp, or in a main CPP for the library
2) instance the global in that file. E.g. in the CPP:
BMC_RNG g_rng;
3) if other modules need to reference it, then add an "extern" (not "inline") declaration in the matching header:
extern BMC_RNG g_rng;

That tells the linker that when a module references g_rng it looks for the symbol in the other modules.

2024-10-09 22:03 UTC, danlangford commented
thank you so much much. I was naively thinking `inline` was something of a shortcut to having the instance in the .cpp and then using `extern`. ill go address ALL the `inline`s 

I appreciate the feedback here

2024-10-10 05:23 UTC, danlangford commented
@pappde ok I think im ready for you to take another pass across this is thats cool with you

2024-10-11 04:23 UTC, pappde requested changes
The main issue is with naming (the prefix) of the globals. Propose the following:

- g_ for global objects that have state, function, etc. E.g. g_qai
- c_ for constant configuration. E.g. c_phase_name
- s_ for tweakable configuration. E.g. s_ply_decay or s_ai_type.

The "m_" prefix should only be used for member variables (meaning defined in the class declaration/ header file).

A couple of other comments were:

2. perhaps m_game should indeed be a member variable of class BMC_Parser
3. BMC_AI::m_qai should probably be moved up a class to BMC_BMAI::m_qai

2024-10-11 04:23 UTC, pappde commented on src/BMC_Parser.cpp
> +BMC_Game m_game(false);
Technically, these are all still "globals" (all the m_* objects), so the "m_" prefix isn't appropriate as it is for member variables of a class.  They aren't visible to other modules, since you don't have an "extern" statement anywhere.   So how they should be handled, either.

A) rename them to "g_*" (e.g. g_game) since that is the prefix for globals
B) move them to be member properties of the BMC_Parser. You would then use the BMC_Parser() ctor to either initialize them directly, or allocate them if using pointers. E.g. as a member object you pass parameters via initializer list
```
BMC_Parser.h
...
    BMC_Game m_game

...
BMC_Parser.cpp
  BMC_Player::BMC_Parser() : m_game(false)
```

As a member pointer, you instead do an explicit new and delete, but the codebase does generally try to avoid this pattern.

UPDATE: 
After observing the "AI" objects are easiest to leave as global (e.g. g_qai), I still think you can go either way with BMC_Game - either as a global or as a member object. The latter is probably cleaner though.

2024-10-11 04:23 UTC, pappde commented on src/BMC_Parser.cpp
> +const char *m_phase_name[BME_PHASE_MAX] =
This is configuration data that is declared globally. The "m_" prefix is for member variables. Configuration should stay global (don't move to a class property), but recommend adopting a "c_" prefix.  E.g.

```
const char *c_phase_name...
```

2024-10-11 04:23 UTC, pappde commented on src/BMC_Logger.cpp
> +const char *g_debug_name[BME_DEBUG_MAX] =
While "g_" is appropriate in this case, I suggested elsewhere the idea of adopting a "c_" prefix for global variables that are constant/configuration.  E.g. *c_debug_name*

2024-10-11 04:23 UTC, pappde commented on src/BMC_Die.cpp
> +INT m_mood_sides_X[BMD_MOOD_SIDES_RANGE_X] = { 4, 6, 8,  10, 12, 20 };
Global configuration. Noted elsewhere these should be "c_mood_sides_X" (if we adopt the convention, or "g_mood..." if not)

2024-10-11 04:23 UTC, pappde commented on src/BMC_Parser.cpp
> +BMC_AI * m_ai_type[BMD_AI_TYPES] = { &m_bmai, &m_qai2, &m_bmai3 };
Prefix "m_" is for member variables. These are global, so the "g_" prefix.  E.g.

```
BMC_QAI g_qai;
```

Recommend leaving the other ones as global as well.

```
BMC_BMAI3 g_ai(&g_qai);
```

2024-10-11 04:23 UTC, pappde commented on src/BMC_Parser.cpp
> +BMC_AI * m_ai_type[BMD_AI_TYPES] = { &m_bmai, &m_qai2, &m_bmai3 };
Per other comments, recommend adopting other prefixes and using "s_ai_type".  Will comment generally about prefixes separately.

2024-10-11 04:23 UTC, pappde commented on src/BMC_BMAI.cpp
> +BMC_BMAI::BMC_BMAI(BMC_AI * _ai) : m_qai(_ai)
I noticed "m_qai" is actually owned by the base class BMC_AI, but is only used by BMC_BMAI.  That property should be moved to the BMC_BMAI class declaration.

2024-10-11 04:30 UTC, pappde commented
Updated review, primarily just naming.  

Moving objects from global to member variables passed via constructors is a good move. Globals generally should be avoided. One thing to remember is that a global is anything defined outside of the class definition. Some things that I believe are ok to stay global:

- all of the configuration/definitions, but I recommended c_ prefixes for these
- singleton type service objects like g_rng and g_logger
- maybe the different AI objects.  You could move them to member variables, but without getting into memory allocation, passing initializer parameters has some limitations.

2024-10-11 04:33 UTC, pappde commented on src/BMC_Parser.cpp
> +BMC_AI * m_ai_type[BMD_AI_TYPES] = { &m_bmai, &m_qai2, &m_bmai3 };
If you wanted to move these to member variables as well, perhaps get away from the constructor initializer list and instead change to explicit initialization. E.g.

```
class BMC_Parser
   ...
   BMC_QAI m_qai
   BMC_BMAI3 m_ai

constructor BMC_Parser::BMC_Parser() : m_game(false)
{
   ...
  m_ai.SetQAI(&m_qai)
}
```

2024-10-11 13:14 UTC, danlangford commented
I know these reviews are big and I really appreciate you taking the time. And they are likely quite annoying. Coming from mainly Java I forget that scoping is different and that just because the .cpp compile unit is primarily focused on class method implementation it doesn’t mean everything in that file is scoped to the class. 🤦

2024-10-16 05:45 UTC, danlangford commented
@pappde I did a pass on some naming.

2024-10-17 22:30 UTC, pappde approved these changes

2024-10-17 22:31 UTC, merged