Morphing Twin & Speed
pappde/bmai pull request #69
Opened 2024-11-07 04:24 UTC by danlangford

2024-11-07 04:37 UTC, danlangford commented on src/BMC_Die.cpp
> -	BM_ERROR( (m_properties & (BME_PROPERTY_MORPHING|BME_PROPERTY_TURBO)) != (BME_PROPERTY_MORPHING|BME_PROPERTY_TURBO) );
I removed this verification but havent tested for it yet.

2024-11-07 13:33 UTC, pappde requested changes
See comments about
1) morphing speed attack being allowed but possibly leaving in invalid state
2) possibly valid assertion that may be worth keeping

2024-11-07 13:33 UTC, pappde commented on src/BMC_Die.cpp
> -	BM_ERROR( !HasProperty(BME_PROPERTY_INSULT) || !m_vulnerabilities.IsSet(BME_ATTACK_SKILL) );
I believe this is a valid assertion. Insult dice cannot be captured with a skill attack.

2024-11-07 13:33 UTC, pappde commented on src/BMC_Die.cpp
> +		if (c_attack_type[_move.m_attack]==BME_ATTACK_TYPE_1_1 || c_attack_type[_move.m_attack]==BME_ATTACK_TYPE_N_1)
What happens if it is not one of these attack types (e.g. Speed)?  

The correct answer presumably is that the attacker must then make a choice which target die to copy.

In this implementation, since there is no "else" case, we will end up in an invalid state (not morphed).  Seems that - in the short term - either:
A) we need to emit an error "unimplemented", or
B) we just morph into a random (or the first) target die then backlog a proper implementation.

2024-11-07 20:09 UTC, danlangford commented on src/BMC_Die.cpp
> +		if (c_attack_type[_move.m_attack]==BME_ATTACK_TYPE_1_1 || c_attack_type[_move.m_attack]==BME_ATTACK_TYPE_N_1)
actually, if you target more than 1 dice the morphing dice just doesn't morph. 

https://www.buttonweavers.com/ui/skills.html#Morphing

> When a Morphing Die is used in any attack against a single target die, it changes size, becoming the same size as the die that was captured. It is then re-rolled.

2024-11-07 20:15 UTC, danlangford commented on src/BMC_Die.cpp
> -	BM_ERROR( !HasProperty(BME_PROPERTY_INSULT) || !m_vulnerabilities.IsSet(BME_ATTACK_SKILL) );
ya I thought about that though and I was concerned that by that logic I might be tempted to create all sorts of assertions that simply double check everything that was done just a few lines before. and I feel that maybe the unit tests is a better place to confirm behavior. but maybe im thinking of things in the wrong light

2024-11-08 04:57 UTC, danlangford commented on src/BMC_Die.cpp
> -	BM_ERROR( (m_properties & (BME_PROPERTY_MORPHING|BME_PROPERTY_TURBO)) != (BME_PROPERTY_MORPHING|BME_PROPERTY_TURBO) );
Morphing and Turbo open up quite a can of worms. not many buttons have that combo. since im looking for low hanging fruit ill leave this combo as unsupported at the moment

2024-11-11 20:04 UTC, pappde commented on src/BMC_Die.cpp
> +		if (c_attack_type[_move.m_attack]==BME_ATTACK_TYPE_1_1 || c_attack_type[_move.m_attack]==BME_ATTACK_TYPE_N_1)
Interesting, when I looked it up I saw this page:
https://buttonmen.fandom.com/wiki/Button_Men_Rules#Morph_Dice:

> Morph Dice copy the size of any die they capture;...

I interpreted this to mean that if multiple dice are captured, they could copy any of them.  

I also checked this page which I believe is the buttonweavers repo:
https://github.com/buttonmen-dev/buttonmen/wiki/Tester-guide:-supported-skills

This isn't clear other than the phrasing "the die" indicating it doesn't cover the multi-dice case.

> m : Morphing - When a Morphing Die is used in any attack, it changes size, becoming the same size as the die that was captured. 

So the first link is probably incorrect.

2024-11-11 20:06 UTC, pappde commented on src/BMC_Die.cpp
> +		if (c_attack_type[_move.m_attack]==BME_ATTACK_TYPE_1_1 || c_attack_type[_move.m_attack]==BME_ATTACK_TYPE_N_1)
RECOMMENDATION
Add a comment to the code (possibly with link) that the code intentionally is only checking the "one target die" case. Otherwise, it looks like an oversight.

2024-11-11 20:09 UTC, pappde commented on src/BMC_Die.cpp
> -	BM_ERROR( !HasProperty(BME_PROPERTY_INSULT) || !m_vulnerabilities.IsSet(BME_ATTACK_SKILL) );
I agree that you don't need to cover requirements in both unit tests and asserts. I see the test.

2024-11-12 00:18 UTC, danlangford commented
Thanks for all your insights. I’ll double back over all this and clean up in a few days.  We have had conversations in other threads about “rule sets” and I wonder if you could consider the specific behavior around morph and multi-die to be implementation specific or a “house rule”. I hear the “old site” morphed into the “right most” die :-)

2024-11-12 07:01 UTC, danlangford commented on src/BMC_Die.cpp
> +		if (c_attack_type[_move.m_attack]==BME_ATTACK_TYPE_1_1 || c_attack_type[_move.m_attack]==BME_ATTACK_TYPE_N_1)
here is further proof that button weavers intentionally does not change the size of a morphing die when there are multiple defenders / targets
https://github.com/buttonmen-dev/buttonmen/blob/master/src/engine/BMSkillMorphing.php#L39-L41
it returns out of the function before the die can morph

2024-11-13 00:33 UTC, pappde commented
> Thanks for all your insights. I’ll double back over all this and clean up in a few days. We have had conversations in other threads about “rule sets” and I wonder if you could consider the specific behavior around morph and multi-die to be implementation specific or a “house rule”. I hear the “old site” morphed into the “right most” die :-)

My biased thought is any scenario that does not allow the user to choose which die to morph to. Meaning either it doesn't morph, or it morphs to a deterministically selected die. Otherwise, that complicates the UI and the AI.  

If there really is no official ruling on the morphing speed scenario, then first priority should be to match what the UI it's running in expects. E.g. "does not morph".

Second priority (meaning backlog) can be to implement a configurable house rule (that is still deterministically selecting the target die). E.g. options are
A) does not morph
B) morphs to largest die
C) morphs to smallest
D) morphs to first
E) morphs to last

I asked ChatGPT and it's "observation" appears to be that there is no official ruling:

> Yes, in Button Men, a morphing die used in a speed attack will still morph to one of the target dice it captures, even if it captures multiple dice in a single attack... When a morphing die captures multiple dice, it usually morphs to the largest die that was captured. However, some players and rules interpretations might allow the player to choose which of the captured dice the morphing die will change into, particularly if there's a tie in size or if it benefits the strategy. It's a good idea to clarify with your opponents before the game starts or refer to any house rules you might be using.

2024-12-02 17:45 UTC, danlangford commented
I was writing a few more unit test and hit a specific case that I’ve been trying to solve. In the middle of all that I got a new computer for work and I’m trying to move some project files over I goofed something up. I lost a couple commits I hadn’t pushed yet. But I think my problems were around single die skill or speed, and not specific to morphing. I’ll try to wrap this up soon.

2024-12-13 18:10 UTC, pappde approved these changes

2024-12-13 18:10 UTC, merged